### PR TITLE
Preparing for the release of the version 19.1

### PR DESCRIPTION
**Pull request by GrayAn**
Greetings!

If I understood correctly this is a required pull request for a new release.

Thanks!

### Contributor Checklist:

* [x] I have updated the release notes at `docs/source/NEWS.rst` 
* [ ] I have updated the automated tests.
* [ ] All tests pass on your local dev environment. See `CONTRIBUTING.rst`.

### CODE REVIEW

**Comment by GrayAn** [comment]
Hi, @psi29a ! I worried a bit, you have not been here for some time.
This PR is ready but I am afraid it is outdated. Maybe I should prepare a new one?

**Comment by psi29a** [comment]
Just bump the day, I can make a release soon.  Dealing with personal issues atm.

**Comment by GrayAn** [comment]
Done. Hope everything is fine or at least can be dealt with...

**Comment by psi29a** [comment]
On this today.

**Comment by psi29a** [comment]
Uploaded!

**Comment by GrayAn** [comment]
Many thanks!

**Pull request merged**
