### PR TITLE
Implement Compare* Functionality

### PR DESCRIPTION
**Pull request by apeschel**
This PR implements the CompareRequest and CompareResponse functionality for both pureldap library and the LDAP server implementation. It also adds testing around the newly implemented features.

### CODE REVIEW

**Comment by psi29a** [comment]
The commits keep on coming. :)

**Comment by cwaldbieser** [comment]
All the tests all pass.  The code logic looks good to me.  `pyflakes` is happy.  `pep8` has a few issues with spaces around keyword argument assignments.  I don't really care about the "line to long" errors it generates unless the line is really, *really* long.

I'd say if `pep8` is made happy (sans line length guidelines), the changes look ready to merge.  I know there is plenty of existing code that makes `pep8` gripe-- don't worry about that (unless you really want to!).

**Comment by psi29a** [comment]
Agreed, we can set the line length to something reasonable like 100 or even 120 to take widescreens into account.

**Comment by apeschel** [comment]
@cwaldbieser Hello, I've made the changes suggested by pep8.

**Comment by cwaldbieser** [comment]
Thanks!  I'll try to take a look tomorrow.

**Comment by cwaldbieser** [comment]
I made a small change for pep8 and merged this with master.  Thanks for your contribution!

**Pull request merged**
