### PR TITLE
Fix implementation of lessOrEqual and greaterOrEqual, plus update tests

### PR DESCRIPTION
**Pull request by aren**

### CODE REVIEW

**Comment by psi29a** [comment]
It seems that isn't passing on Twisted's latest code in trunk/master.

**Comment by psi29a** [comment]
```
ldaptor.test.test_merger.MergedLDAPServerTest.test_bind_one_invalid
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/travis/build/twisted/ldaptor/ldaptor/test/test_merger.py", line 91, in test_search_merged
    LDAPSearchResultDone(ldaperrors.Success.resultCode)]])
  File "/home/travis/build/twisted/ldaptor/ldaptor/test/test_merger.py", line 43, in createMergedServer
    server.connectionMade()
  File "/home/travis/build/twisted/ldaptor/ldaptor/protocols/ldap/merger.py", line 88, in connectionMade
    overrides=c.getServiceLocationOverrides())
  File "/home/travis/build/twisted/ldaptor/ldaptor/protocols/ldap/ldapconnector.py", line 113, in connect
    bindAddress=bindAddress)
  File "/home/travis/build/twisted/ldaptor/ldaptor/protocols/ldap/ldapconnector.py", line 39, in __init__
    connectFuncKwArgs={'bindAddress': bindAddress})
  File "/home/travis/build/twisted/ldaptor/.tox/py27-twtrunk/lib/python2.7/site-packages/twisted/names/srvconnect.py", line 77, in __init__
    self.domain = nativeString(domain)
  File "/home/travis/build/twisted/ldaptor/.tox/py27-twtrunk/lib/python2.7/site-packages/twisted/python/compat.py", line 358, in nativeString
    raise TypeError("%r is neither bytes nor unicode" % s)
exceptions.TypeError: None is neither bytes nor unicode
```

**Comment by aren** [comment]
Yeah I'm seeing the same test failure on the ldaptor master (without these changes).

**Comment by psi29a** [comment]
LGTM, what do you think @cwaldbieser ?

**Comment by cwaldbieser** [comment]
I agree-- looks good.  Missing `.values` were added when needed, and BER wrappers were placed around values, which is presumably what *really* should be compared.

**Pull request merged**
