### PR TITLE
don't build readthedocs epub

### PR DESCRIPTION
**Pull request by graingert**
Change suggested by @adiroiban, I'm -0 on this as it's not doing too much harm

### Contributor Checklist:

* [ ] I have updated the release notes at `docs/source/NEWS.rst`
* [ ] I have updated the automated tests.
* [ ] All tests pass on your local dev environment. See `CONTRIBUTING.rst`.

### CODE REVIEW

**Review by adiroiban — APPROVED** [review]
I am +1 since I hope that with this we get a green Read the docs badge.

I like to check the readme or github repo start page and see the status of all the tests.

I now see that we don't run the read the docs tests on a merge in master.
Not sure if that is on purpose... or this is how read that docs works

Does read the docs run the commit tests only for a PR, or it can also run the tests and send a commit status for a push/merge?

image

**Comment by graingert** [comment]
> I am +1 since I hope that with this we get a green Read the docs badge.

The readthedocs badge is already green

**Comment by adiroiban** [comment]
If Read the docs is not creating the EPUB during a PR tests, I think is best have this merged. Thanks!

**Comment by glyph** [comment]
I'm 👍 on green checkmarks

**Comment by glyph** [comment]
I would have merged this but python3.6 has been removed from github actions so the build config needs to be updated first :(

**Comment by psi29a** [comment]
Going to push this through, it removal of epub creation which has no effect on code itself.

**Pull request merged**
