### PR TITLE
LDAPSearchResultReference basic implementation

### PR DESCRIPTION
**Pull request by GrayAn**
This PR is a fix for issue #144 . `LDAPSearchResultReference` class was not fully implemented and did not have tests before (so I accidently broke it while porting `pureldap` code for Python 3). I attempted to implement it accordingly to the [RFC](https://tools.ietf.org/html/rfc4511#section-4.5.3) but not sure if it really works: I need a LDAP server with this feature to test it (Active Directory for example).

### Contributor Checklist:

* [x] I have updated the release notes at `docs/source/NEWS.rst` 
* [x] I have updated the automated tests.
* [x] All tests pass on your local dev environment. See `CONTRIBUTING.rst`.

### CODE REVIEW

**Comment by GrayAn** [comment]
Well, this time I have no idea what codecov does not like :)

**Comment by psi29a** [comment]
Can anyone who has access to an AD, can they test this code against it?

**Comment by cwaldbieser** [comment]
I'll try to take a look at it.

**Comment by cwaldbieser** [comment]
Hmm-- I'm not sure I can generate a query that will create an LDAP Search Result reference.  I do have access to an AD, but it is just  a single, unpartitioned domain.  Is there some way to create an reference entry that can be queried?

On a different note, I ran into a number of cases where I got an error similar to the one in #144.

> During handling of the above exception, another exception occurred:

It looks like all the exceptions being raised inherit from `ldaperrors.LDAPException`.  That class has had its `__str__()` implementation switched to `toWire()`, but that doesn't seem right-- the exception handling code in Twisted seems to expect an exception that can be printed:

    Traceback (most recent call last):
      File "/home/waldbiec/.virtualenvs/txldap_ad_client-hpiTWo4R/lib/python3.6/site-packages/twisted/python/reflect.py", line 448, in safe_str
        return str(o)
    TypeError: __str__ returned non-string (type bytes)

I got this error during StartTLS negotiation and when I tried to query the rootDSE and got a "NO SUCH OBJECT" response.  In the former case, the issue seems to be similar to the 2nd error described in #144.

In the `protocols.ldap.ldapclient.LDAPClient._cbStartTLS()` callback, the comparison between `msg.responseName` and `pureldap.LDAPStartTLSResponse.oid` fails because one is a byte-string and the other is a unicode string.  If I decoded `msg.responseName` to UTF-8 first, the comparison worked as I would have expected.

I only tried this in python 3.  I've been weaning myself off python 2.7 this year.

**Comment by GrayAn** [comment]
Thanks @cwaldbieser !

I fixed these issues in the other pull requests: #146 and #147 .

**Comment by GrayAn** [comment]
One of my colleagues gave me an access to his Active Directory test instance. And luckily it responded with a `LDAPSearchResultReference` message to the search request:
```
C->S LDAPMessage(id=2, value=LDAPSearchRequest(baseObject=u'cn=configuration,dc=foo,dc=kama,dc=gs', scope=2, derefAliases=0, sizeLimit=0, timeLimit=0, typesOnly=0, filter=LDAPFilter_present(value='objectClass'), attributes=('objectClass',)), controls=None)
C<-S LDAPMessage(id=2, value=LDAPSearchResultEntry(objectName='CN=Configuration,DC=foo,DC=kama,DC=gs', attributes=[('objectClass', ['top', 'configuration'])], controls=None)
...
C<-S LDAPMessage(id=2, value=LDAPSearchResultReference(uris=[LDAPString(value='ldap://foo.kama.gs/CN=Schema,CN=Configuration,DC=foo,DC=kama,DC=gs')]), controls=None)
C<-S LDAPMessage(id=2, value=LDAPSearchResultDone(resultCode=4), controls=None)
```
I tried it on Python 2.7 and 3.6 versions.
Looks like it actually works, not only in the tests :)

**Comment by cwaldbieser** [comment]
Thanks, this looked good to me.  It's good to know this actually worked against a real example!

**Comment by GrayAn** [comment]
Thank you! Maybe we can make a release? There was a number of [bug fixes](https://github.com/twisted/ldaptor/blob/master/docs/source/NEWS.rst#release-191-unreleased) since the last release.

**Comment by psi29a** [comment]
Glad this was tested against something live.

Is everyone on board for another release?

**Comment by cwaldbieser** [comment]
Yes, a release seems prudent.

**Pull request merged**
