### PR TITLE
add new shields.io badges for travis, github, rtd and pypi

### PR DESCRIPTION
**Pull request by graingert**
### Contributor Checklist:

* [ ] I have updated the release notes at `docs/source/NEWS.rst`
* [ ] I have updated the automated tests.
* [ ] All tests pass on your local dev environment. See `CONTRIBUTING.rst`.

### CODE REVIEW

**Review by adiroiban — APPROVED** [review]
I have tested this by checking the readme rendering from the branch at https://github.com/graingert/ldaptor/tree/add-shields

I think that Travis can be removed, as the travis-ci will be removed soon.

Not sure why readthedocs badge is red.

Thanks

**Review by psi29a — CHANGES_REQUESTED** [review]
I agree, if we are going to use github only hooks and no travis, then the travis badge should go.

**Comment by graingert** [comment]
Currently ldaptor requires Travis to test using python v2.7, once that requirement is gone I'll remove all record of Travis in one go

**Comment by graingert** [comment]
> Not sure why readthedocs badge is red.

I posted this elsewhere but for other's reference it was because the epub builds failed which are not run in PRs https://github.com/readthedocs/readthedocs.org/issues/7116

**Comment by adiroiban** [comment]
I think that this can be merges as it is. My comment about travis shield was just a suggestion. 

Travis is still required at this time, as py2 is not yet removed in master.

---------

regarding read the docs... can we disable the epub file generation from read the docs config file? Maybe as a drive-by to this PR?

Thanks!

**Pull request merged**
