### PR TITLE
replace pycrypto with passlib Fixes #2

### LINKED ISSUE #2: replace PyCrypto usage with PyCA's Cryptography

### PR DESCRIPTION
**Pull request by graingert**
## Remove this paragraph

Please have a look at our dev docs before submitting your PR:
https://github.com/twisted/ldaptor/blob/master/CONTRIBUTING.rst

### Contributor Checklist:

* [ ] I have updated the release notes at `docs/source/NEWS.rst` 
* [x] I have updated the automated tests.
* [x] All tests pass on your local dev environment. See `CONTRIBUTING.rst`.

### CODE REVIEW

**Comment by psi29a** [comment]
Sweet! Thank you for all the hard work!

**Comment by psi29a** [comment]
Just had time to review and validate, LGTM! Thank you @graingert  :)

**Comment by graingert** [comment]
@psi29a any chance of a release?

**Comment by psi29a** [comment]
I believe so, we'll be making a 19 release, not a 18 release since we're 2019 now. :)

What do you think guys? 
@cwaldbieser @GrayAn

**Comment by GrayAn** [comment]
@psi29a It is okay I think. I was planning to make several naming fixes concerning Python 3 compatibility (see our discussion with @adiroiban : [first](https://github.com/twisted/ldaptor/pull/135#discussion_r238055788) and [second](https://github.com/twisted/ldaptor/pull/136#discussion_r239175542) but did not find enough time to solve them out.

**Comment by psi29a** [comment]
We can always make point releases to address these issues later.

**Comment by adiroiban** [comment]
I think that is about time to bite the bullet and make a new release :)
I am still using 16.0.0 in my prod environment.
I did not had time to test the latest master as I was waiting for more changes to accumulate... but If a new releases is planed, I can give it a try

**Comment by psi29a** [comment]
Give it a go, 19.0 is live on pypi

If there are issues, let me know then we'll work through them for 19.1

**Comment by adiroiban** [comment]
Can we have a tag created for this ? :)
Maybe use Travis-CI to automatically publish to PyPI for each newly created tag... in this way, the release is automatic and we have tags :)

**Comment by psi29a** [comment]
Done!

**Comment by cwaldbieser** [comment]
Yes, we've quite a few changes since the last release.  I think the time is right.

**Comment by adiroiban** [comment]
I have tested the latest release and it looks good.

The `LDAPEntryWithClient.__str__()` warning is ok...but we nice to raise the error with the previous stack to see from where it is called.
For me it was easy to fix as I was using it from a single place :)

**Comment by GrayAn** [comment]
> The `LDAPEntryWithClient.__str__()` warning is ok...but we nice to raise the error with the previous stack to see from where it is called.

I have just [fixed it](https://github.com/twisted/ldaptor/pull/143) :)

**Pull request merged**
