### PR TITLE
Add example for AD like BIND.

### PR DESCRIPTION
**Pull request by adiroiban**
Scope
=====

See the discussion from #78 

Changes
=======

I have moved all examples into a single place.

I chose that single place to be the Sphinx source so that it is easy to reference them from the source documentation.

I prefer `literalinclude` as I find it easier to manage and in this way is easier to test the examples.

I have converted the examples into a module to make it easier to import it during tests.

For the tests, I am messing with the sys.path.

I don't know if trial has something like tearDownModule ... so I don't know how to do the cleanup.
I hope that there is no harm in this.

As a drive-by, I have creates a tox env for building the documentation so that we can have a canonical name to create the docs.

As a drive-by I added the travis-ci badge to README as it makes it easier to check if master is green.

How to check
==========

Let me know if you are ok with the drive-by changes. Not sure why the examples were outside of docs/source in the first place :)

I wrote the test, so I hope that in this way the example will stay up to date.

### CODE REVIEW

**Comment by adiroiban** [comment]
should be ready for review. I see that master is failing on pypi

needs-review

**Comment by psi29a** [comment]
Fixed pypy (by removing it for now)

**Comment by cwaldbieser** [comment]
Made a couple small edits-- typo in "bobby", altered phrasing in a few comments.  It was a good example of how you can intercept an LDAP request and adapt it to features of the back end.  

Thanks, for contributing!

**Comment by adiroiban** [comment]
Thanks for the review and thanks for keeping ldaptor alive :)

**Pull request merged**
