### PR TITLE
Python 3 compatibility fix for schema and fetchschema modules (second attempt)

### PR DESCRIPTION
**Pull request by GrayAn**
Greetings!

While fixing quick start example to make it Python 3 compatible I found some inconsistencies in ldapsyntax module. But before I can fix them I need to make its dependent fetchschema and schema modules Python 3 compatible as they were still using strings instead of explicit byte strings. Additional test cases for test_schema were implemented as the changes in schema module affected some lines not covered by tests.

The previous PR has caused "unexpected coverage difference" (increase actually) in codecov. This one has some additional changes in `test_server` which I hope will pass.

### Contributor Checklist:

* [x] I have updated the release notes at `docs/source/NEWS.rst` 
* [x] I have updated the automated tests.
* [x] All tests pass on your local dev environment. See `CONTRIBUTING.rst`.

### CODE REVIEW

**Comment by GrayAn** [comment]
codecov/patch was unsuccessful but its details don't show any coverage changes. I looked through [schema.py](https://codecov.io/gh/twisted/ldaptor/compare/b3881177870978906be5a6454fa7cb60ea08c8c5...31f83fb9bc0c121b788e913b039f097687b4c1fc/src/ldaptor/schema.py?before=ldaptor/schema.py), perhaps I need to write more tests...

**Comment by psi29a** [comment]
I sometimes think that codecov is too strict...

**Comment by psi29a** [comment]
Looks like adding more test coverage tipped codecov into your favor.  Thank you!

**Comment by GrayAn** [comment]
Oops, I forgot to test it on Python 3, will be fixed soon.

**Comment by GrayAn** [comment]
Yes, it works!

**Comment by psi29a** [comment]
Travis-CI is also happy ;) (was waiting for it too)

**Pull request merged**
