### PR TITLE
fixes #70 Assign correct types to LDAPMatchingRuleAssertion members.

### LINKED ISSUE #70: Malformed packet for LDAPFilter_extensibleMatch
```
from ldaptor.ldapfilter import parseFilter
from pyasn1.codec.ber import decoder

l = parseFilter('(ou:=test)')
print repr(l)

print decoder.decode(str(l))
```

result:

```
LDAPFilter_extensibleMatch(matchingRule=None, type='ou', matchValue='test', dnAttributes=None)
Traceback (most recent call last):
  File "test_ber.py", line 10, in <module>
    print decoder.decode(str(l))
  File "/usr/lib64/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 825, in __call__
    stGetValueDecoder, self, substrateFun
  File "/usr/lib64/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 50, in valueDecoder
    value, _ = decodeFun(head, asn1Spec, tagSet, length)
  File "/usr/lib64/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 706, in __call__
    '%d-octet short' % (length - len(substrate))
pyasn1.error.SubstrateUnderrunError: 113-octet short
```

### PR DESCRIPTION
**Pull request by tonich-sh**

### CODE REVIEW

**Comment by psi29a** [comment]
Looks like this commit causes a few failures. Can you take a look at them please?  There are expected return values that have changed.

**Comment by cwaldbieser** [comment]
Yes-- something is not behaving deterministically across testing platforms.  If I run the tests on my workstation for Python 2.7, they succeed.  I'll look at PR #72 and see if that makes the tests make more sense.

**Comment by cwaldbieser** [comment]
Ran the tests and everything looked good.  Thanks for your contribution!

**Comment by psi29a** [comment]
@tonich-sh thanks!

**Pull request merged**
