### PR TITLE
drop direct dependency on pyOpenSSL

### PR DESCRIPTION
**Pull request by graingert**
## Remove this paragraph

Please have a look at our dev docs before submitting your PR:
https://github.com/twisted/ldaptor/blob/master/CONTRIBUTING.rst

### Contributor Checklist:

* [x] I have updated the release notes at `docs/source/NEWS.rst` 
* [ ] I have updated the automated tests.
* [ ] All tests pass on your local dev environment. See `CONTRIBUTING.rst`.

### CODE REVIEW

**Comment by psi29a** [comment]
Sweet, thanks for catching this and taking care of it.

**Comment by psi29a** [comment]
Ready?  

Just a hint, if you think you are still going to push to a PR, you can put [WIP] in the title and github prevent it from being merged until the creator of the PR is ready. :)

**Comment by graingert** [comment]
@psi29a ready

**Comment by psi29a** [comment]
uploaded to pypi, ldaptor 19.0 is shipped
thanks for your hard work! :)

**Pull request merged**
