### PR TITLE
Style cleanup in preparation for python3 port.

### PR DESCRIPTION
**Pull request by adiroiban**
Scope
========

As part for #55 @psi29a  has created https://github.com/psi29a/ldaptor/tree/python3 but beside py3 changes it contains a lot of non-py3 changes.

That branch hasa conflict with latest master so make a future merge simpler this takes those non-py3 changes

You can see the diff here https://github.com/twisted/ldaptor/compare/master...psi29a:python3

Changes 
=======

I tried to only put non-controversial changes.

For some simple cases I tried to update the way raises is used, but this is not a complete change for all exception raising or catching.

In preparation for py3 unit testing I have renamed all assertEquals to assertEqual

How to check
=============

This is huge but I hope that most of the changes will only need time to check.

### CODE REVIEW

**Comment by psi29a** [comment]
LGTM, this needed to be done for readability. It's also a great exercise in reading and understanding the codebase. :)

**Comment by psi29a** [comment]
Next PR, I would like to see an update to the Changelog if you could. Even for cleanups. :)

**Comment by adiroiban** [comment]
> Next PR, I would like to see an update to the Changelog if you could. Even for cleanups. :)

I checked the CONTRIBUTING docs but there was no reference about docs/source/NEWS.rst

I will try to document it as part of the next PR

**Comment by adiroiban** [comment]
> LGTM, this needed to be done for readability. It's also a great exercise in reading and understanding the codebase. :)

I haven't checked the codebase. For me this was mechanical work.
I agree that cleanup is needed... looking forward for adding pep8 checks to not regress on this.

**Pull request merged**
