### PR TITLE
Python 3 support for LDAPServer

### PR DESCRIPTION
**Pull request by GrayAn**
Greetings!

This is an another step to Python 3 support. It mostly consists of switching from ``__str__`` to ``toWire`` method. I also had to implement here a feature which may be considered somewhat ugly: attributes can be got from entry by their bytes or unicode representation regardless of how they are stored in it. It helped to implement Python 3 support for LDAP search.

### Contributor Checklist:

* [x] I have updated the release notes at `docs/source/NEWS.rst` 
* [x] I have updated the automated tests.
* [x] All tests pass on your local dev environment. See `CONTRIBUTING.rst`.

### CODE REVIEW

**Comment by psi29a** [comment]
Looks like this is an out-of-date branch with master...

**Comment by GrayAn** [comment]
Fixed!

**Comment by psi29a** [comment]
You're killing it! :) :+1:

**Comment by GrayAn** [comment]
Thanks!

**Pull request merged**
